/*
    imgSrc,
    name,
    designation,
    linkedIn,
    insta,
    github,
    contact number,
    email id
*/

export const CoreData = [
    {
      name: "Shreyans Jain",
      imgSrc: "/team/sj.jpeg",
      designation: "Sponsorship Core",
      email: "",
      number: "+91 ",
      linkedin: "",
      insta: "",
    },
    {
      name: "Pratham Sharda",
      imgSrc: "/team/ps.jpeg",
      designation: "Marketing Core",
      email: "debojit.das@iitgn.ac.in",
      number: "+91 96090 18007",
      linkedin: "https://www.linkedin.com/in/debojitdas842/",
      insta: "https://instagram.com/the_quirky_munda",
    },
    {
      name: "Balagopal",
      imgSrc: "/team/Bg.jpg",
      designation: "Sponsorship Core",
      email: "debojit.das@iitgn.ac.in",
      number: "+91 96090 18007",
      linkedin: "https://www.linkedin.com/in/debojitdas842/",
      insta: "https://instagram.com/the_quirky_munda",
    },
    {
      name: "Parth Govale",
      imgSrc: "/team/pg.jpg",
      designation: "Design Core",
      email: "parth.govale@iitgn.ac.in",
      number: "+91 96198 69044",
      linkedin: "https://www.linkedin.com/in/parth-govale-a65120277/",
      insta: "https://instagram.com/parth_govale",
    },
    {
      name: "Saransh Sharma",
      imgSrc: "/team/Saransh.jpg",
      designation: "Content for Talk Core",
      email: "guntassingh.saran@iitgn.ac.in",
      number: "+91 73409 64064",
      linkedin: "https://www.linkedin.com/in/guntas-singh-saran-2b8811179/",
      insta: "https://www.instagram.com/guntas.saran13/",
    },
    {
      name: "Tilak Maheshwari",
      imgSrc: "/team/Tilak.jpg",
      designation: "Events Production Core",
      email: "mangalampalli.narayana@iitgn.ac.in",
      number: "+91 99201 32149",
      linkedin: "https://www.linkedin.com/in/agastya-narayana/",
      insta: "https://www.instagram.com/augustyeah",
    },
    {
      name: "Dhruvi Sisodiya",
      imgSrc: "/team/dhruvi.jpg",
      designation: "Design Core",
      email: "mangalampalli.narayana@iitgn.ac.in",
      number: "+91 99201 32149",
      linkedin: "https://www.linkedin.com/in/agastya-narayana/",
      insta: "https://www.instagram.com/augustyeah",
    },
    {
      name: "Darshan Zhala",
      imgSrc: "/team/darshan.jpg",
      designation: "Finance Core",
      email: "mangalampalli.narayana@iitgn.ac.in",
      number: "+91 99201 32149",
      linkedin: "https://www.linkedin.com/in/agastya-narayana/",
      insta: "https://www.instagram.com/augustyeah",
    },
  ];
  
  export const TechTeamData = [
    {
      name: "Jayraj Dulange",
      imgSrc: "./Images/parth.webp",
      designation: "Web Developer",
      email: "parth.govale@iitgn.ac.in",
      number: "+91 96198 69044",
      linkedin: "https://www.linkedin.com/in/parth-govale-a65120277/",
      insta: "https://instagram.com/parth_govale",
      github: "https://github.com/Demolus13"
    },
    {
      name: "Vraj Shah",
      imgSrc: "./Images/vraj.webp",
      designation: "Web Developer",
      email: "vraj.shah@iitgn.ac.in",
      number: "+91 94846 38348",
      linkedin: "https://www.linkedin.com/in/vraj-shah-6a634a254/",
      insta: "https://www.instagram.com/vraj_shah_2811/",
      github: "https://github.com/Vraj2811"
    },
    {
      name: "Rachit Mehta",
      imgSrc: "./Images/dipesh.webp",
      designation: "Web Developer",
      email: "dipesh.patidar@iitgn.ac.in",
      number: "+91 62649 38418",
      linkedin: "https://www.linkedin.com/in/dipesh-patidar-586133256/",
      insta: "https://www.instagram.com/_dipesh_patidar_",
      github: "https://github.com/dipesh6264",
    },
    {
      name: "Chandrabhan Patel",
      imgSrc: "./Images/pranav.webp",
      designation: "Web Developer",
      email: "pranav.joshi@iitgn.ac.in",
      number: "+91 86989 55551",
      linkedin: "",
      insta: "https://instagram.com/ik_sm_stuff",
      github: "https://github.com/PJ29072004",
    },
    {
      name: "Romit Mohane",
      imgSrc:
        "https://media.licdn.com/dms/image/D4D03AQEcT-uVrr0xRw/profile-displayphoto-shrink_800_800/0/1695235027134?e=1701302400&v=beta&t=IxXPN2YQlRVv4c3-2QCBcDSJLkz9viYjj_yWtDtHTpM",
      designation: "Web Developer",
      email: "23110279@iitgn.ac.in",
      number: "+91 84258 05555",
      linkedin: "https://www.linkedin.com/in/romit-mohane/",
      insta: "https://instagram.com/its_romit.m",
      github: "https://github.com/Reckadon",
    },
  ];